version: "3.8"

services:
  redis-db:
    image: redis:7.0
    container_name: midterm-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: ["redis-server", "--bind", "0.0.0.0"]

  flask-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: midterm-flask
    depends_on:
      - redis-db
    environment:
      REDIS_HOST: redis-db
      REDIS_PORT: 6379
    ports:
      - "5001:5000"

